# Generated by Django 5.1.2 on 2025-03-19 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='junctions/illustrations/')),
                ('story', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='junctions/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junctions', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junctions', to='music.track')),
            ],
        ),
    ]
